# Site settings
title: "Ben Johnson"
description: > # this means to ignore newlines until "baseurl:"
  Ben Johnson is an iOS developer in Lancaster, PA.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://benrobjoh.com" # the base hostname & protocol for your site
github_username:  benrobjoh
company_name: Bixelcog LLC
company_url: http://www.bixelcog.com

# Build settings
markdown: kramdown
